# Site settings
title: Mitchell's Segmentation Fault. #'
email: mitchell.mohorovich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A blog for the aimless thoughts of Mitchell Mohorovich. 
   ğŸ˜


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imiith.github.io" # the base hostname & protocol for your site
twitter_username: iMiiTH
github_username:  iMiiTH

# Build settings
markdown: kramdown
